#!/bin/bash
# START HELP
# A script to help git repositories stay up to date with a different remote.
#
# If the git repository is configured to have a remote named "source", this script
# will pull the master branch of that repo, and reset the current branch of master
# to that branch.
# END HELP
set -e
BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
if [ $# -gt 1 ]; then
    BRANCH="$1"
fi
git fetch upstream
git checkout "$BRANCH"
git reset --hard "upstream/$BRANCH"