#!/usr/bin/env python
# SUMMARY: print recent branchs checked out.
import subprocess
import sys

seen = set()
lines = []
output = subprocess.check_output("git log -g --oneline --decorate-refs='refs/heads' --pretty=format:'%d: %s' -100", shell=True)
for l in str(output).split("\n"):
    if not l.startswith(" ("):
        continue
    if l in seen:
        continue
    seen.add(l)
    lines.append(l)

print("\n".join(lines))