#!/bin/bash
# SUMMARY: configure the window environment to be used in a dock
# START HELP
# after calling this, applications will have to be restarted to honor
# new configuration
# END HELP
# load configuration for laptop when docked
xrandr --output eDP-1 --off --output DP-1 --auto --output DP-2 --right-of DP-1