packages:
  # fish shell, which I prefer to use.
  - name: fish
    ppa: "fish-shell/release-4"
  # helpful utility to visualize disk usage.
  - name: ncdu
  # window manager I prefer to use
  - name: sway
  # for IME support
  - name: fcitx5
  - name: fcitx5-mozc # for Japanese input
  # file manager
  - name: thunar
  # for getting cpu stats
  - name: sysstat
  # for docker containers
  - name: podman
  - name: podman-docker
packages_binstall:
  - "jj-cli"
binaries:
  - name: "cursor"
    # v 1.0
    url: "https://downloads.cursor.com/production/53b99ce608cba35127ae3a050c1738a959750865/linux/x64/Cursor-1.0.0-x86_64.AppImage"
    sha256: "1c9893dda0c1eba2b6b257062430b6d7e5a12bf92fe0a08a55982ea5b7e62c6d"
  - name: "bazelisk"
    url: "https://github.com/bazelbuild/bazelisk/releases/download/v1.26.0/bazelisk-linux-amd64"
