packages:
  # fish shell, which I prefer to use.
  - name: fish
    ppa: "fish-shell/release-4"
  # helpful utility to visualize disk usage.
  - name: ncdu
  # window manager I prefer to use
  - name: sway
  # for IME support
  - name: fcitx5
  - name: fcitx5-mozc # for Japanese input
  # file manager
  - name: thunar
  # for getting cpu stats
  - name: sysstat
  # for docker containers
  - name: podman
  - name: podman-docker
  # install some dependencies for other packages normally installed by .dep
  - name: miniupnpc
packages_binstall:
  - "jj-cli"
binaries:
  - name: "cursor"
    # v 1.0
    url: "https://downloads.cursor.com/production/53b99ce608cba35127ae3a050c1738a959750865/linux/x64/Cursor-1.0.0-x86_64.AppImage"
  - name: "bazelisk"
    url: "https://github.com/bazelbuild/bazelisk/releases/download/v1.26.0/bazelisk-linux-amd64"
  # cli for confighub
  # didn't work, just install the CLI: curl -fsSL https://hub.confighub.com/cub/install.sh | bash
  # - name: "cub"
  #   url: "https://confighub-downloads-6554c6cc.s3.amazonaws.com/public/cub-linux-amd64-latest"
  #   sha256: "41f28969cc044faf8a3cf2b24f5c11614eda8f4f5fd67b25347e7658c9e50f22"
