#!/usr/bin/env bash
# SUMMARY: create a new branch from the upstream main branch
branch="$1"

if [ -z "$branch" ]; then
  echo "Usage: $0 <branch>"
  exit 1
fi

UPSTREAM=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
if [ $# -gt 1 ]; then
    UPSTREAM="$1"
fi

git checkout -b "$branch" "$UPSTREAM"