#!/bin/bash
# SUMMARY: configure the window environment to be used in a dock
# START HELP
# after calling this, applications will have to be restarted to honor
# new configuration
# END HELP
# load configuration for laptop when docked
xrandr --output eDP-1 --mode 3840x2160 --output DP-1 --mode 3840x2160 --right-of eDP-1