#!/bin/bash
# SUMMARY: configure the window environment to be used in a dock
# START HELP
# after calling this, applications will have to be restarted to honor
# new configuration
# END HELP
# load configuration for laptop specifically
xrandr --output eDP-1 --mode 3840x2160