#!/usr/bin/env bash
qmk json2c ./other-configuration/ergodox.json -o /home/tsutsumi/qmk_firmware/keyboards/ergodox_ez/keymaps/yusuke/keymap.c
qmk json2c ./other-configuration/ergodox.json -o /home/tsutsumi/qmk_firmware/keyboards/hotdox/keymaps/yusuke/keymap.c

# to flash, choose the keyboard here
# also could flash -kb ergodox_ez
qmk compile -kb hotdox -km yusuke
qmk flash -kb hotdox -km yusuke
