#!/usr/bin/env bash
#
# This script scopes vpn traffic to only private IPV4 address space.
# This saves traffic going through the VPN for public services
# like teleconferencing.
#
# This script needs to run as a user with privileges to
# modify ip route table. root definitely works.

# standard variables to specify this traffic should go
# through the VPN. openconnect labels the device as tun0.
VPN_VARS="dev tun0 scope link"

ip route del default $VPN_VARS
ip route add 10.0.0.0/8 $VPN_VARS
ip route add 172.16.0.0/12 $VPN_VARS
ip route add 192.168.0.0/16 $VPN_VARS